[package]
name = "localhost"
version = "0.1.0"
edition = "2021"

[dependencies]
tera = "1.20.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
toml = "0.8.19"
libc = "0.2.160"
kqueue = "1.0.8"

