# ----- Code Complexity -----

# Maximum cognitive complexity a function can have
# Default: 25
cognitive-complexity-threshold = 20

# Maximum allowed size for enum variants
# Default: 200 bytes
enum-variant-size-threshold = 200

# Maximum number of arguments a function can have
# Default: 7
too-many-arguments-threshold = 6


# ----- Code Style -----

# Type names that are not considered as blacklisted
# Default: empty list
doc-valid-idents = ["ClipPy", "OAuth", "GraphQL", "ECMAScript", "IPv4", "IPv6"]

# Maximum number of lines for a single function
# Default: 100
too-many-lines-threshold = 100


# ----- Performance -----

# Maximum size (in bytes) for passing an array by value
# Default: 512
array-size-threshold = 512


# ----- Type System -----

# Maximum complexity threshold for type definitions
# Default: 250
type-complexity-threshold = 250


# ----- Documentation -----

# Requires every public item to be documented
# Default: false
deny-missing-docs = true


# ----- Test Configuration -----

# Allows certain non-standard naming conventions
# Default: false
allow-unwrap-in-tests = true

# Configure specific lints to be more permissive in tests
[test]
too-many-arguments-threshold = 12
