[[servers]]
dns = "localhost"
host = "0.0.0.0"
ports = [8080]
root = "$CARGO_MANIFEST_DIR/public"
uploads = 10485760
listing = true

[servers.router]
cgi = { ".py" = "explorer" }

[[servers.router.routes]]
path = "/"
methods = ["GET", "POST"]
session = true
redirect = { "/auth" = "auth.html" }

[[servers.router.routes]]
path = "/auth"
methods = ["GET"]
default_file = "auth.html"
session = false

[[servers.router.routes]]
path = "/upload"
methods = ["GET", "POST"]
session = false

[[servers]]
dns = "public-web-server"
host = "0.0.0.0"
ports = [8081]
root = "$CARGO_MANIFEST_DIR/public"
errors = { 400 = "400.html", 403 = "403.html", 404 = "404.html", 405 = "405.html" }
uploads = 10485760
listing = false

# [server.router]

[[servers.router.routes]]
path = "/"
methods = ["GET"]
default_file = "index.html"
session = true
redirect = { auth = "auth.html" }

[[servers.router.routes]]
path = "/auth"
methods = ["GET"]
default_file = "auth.html"
session = false
