[server]
name = "default"
host = "127.0.0.1"
ports = [8080, 3000, 5500]
timeout = 2500
methods = ["GET", "POST", "DELETE"]

[[servers]]
name = "server_1"
ports = [8080, 3000]
timeout = 5000
methods = ["GET", "POST"]

[[servers]]
name = "server_2"
ports = [5500, 4000]
host = "0.0.0.0"
timeout = 3000
method = ["GET"]

[[servers]]
name = "server_3"
ports = [4000, 8080]
