[[servers]]
host = "127.0.0.1"
ports = [8080, 5500, 4000, 8000]
root = "$CARGO_MANIFEST_DIR/public"
error_pages = ["404.html", "400.html", "405.html", "403.html"]
uploads_max_size = 10485760
cgi = { "py" = "/python-cgi.py" }
listing = true

[[servers.routes]]
path = "/"
methods = ["GET"]
default_file = "index.html"
check_session = true
redirect = { "/login/" = "signin.html" }

[[servers.routes]]
path = "/login/"
methods = ["GET", "POST"]
default_file = "signin.html"
check_session = false

[[servers.routes]]
path = "/register/"
methods = ["GET", "POST"]
default_file = "signup.html"
check_session = false

[[servers.routes]]
path = "/logout/"
methods = ["POST", "DELETE"]
default_file = "signout.html"
check_session = false

# [[servers]]
# host = "127.0.1.1"
# ports = [8080, 3000]
# timeout = 3000
