[[servers]]
host = "127.0.0.1"
ports = [8080, 3000]
methods = ["GET", "POST", "DELETE"]
timeout = 5000

[[servers]]
host = "192.168.20.10"
port = [5500, 4000]
methods = ["GET"]
timeout = 3000

[[servers]]
host = "0.0.0.0"
ports = [4000, 8080]
methods = ["POST"]
timeout = 4500
